# Generated by Django 4.0.3 on 2022-04-28 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PseudomonGo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnimalRating',
            new_name='Rating',
        ),
    ]
