# Generated by Django 4.0.3 on 2022-04-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PseudomonGo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
