# Generated by Django 4.0.3 on 2022-04-28 23:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PseudomonGo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_location',
            field=models.CharField(default='UMBC', max_length=50, verbose_name='Sighted Location'),
        ),
        migrations.AddField(
            model_name='animal',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='photo_path',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
        migrations.DeleteModel(
            name='AnimalImage',
        ),
        migrations.AddField(
            model_name='rating',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PseudomonGo.animal'),
        ),
    ]
