# Generated by Django 4.0.3 on 2022-05-11 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PseudomonGo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='attack',
            new_name='base_atk',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='defense',
            new_name='base_def',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='health',
            new_name='base_hp',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='speed',
            new_name='base_spd',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='name',
            new_name='entity_name',
        ),
    ]
