# Generated by Django 4.0.3 on 2022-04-13 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PseudomonGo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=50)),
                ('entity_desc', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EntityClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('class_description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=25)),
                ('item_type', models.CharField(max_length=25)),
                ('item_description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_name', models.CharField(max_length=50)),
                ('base_damage', models.IntegerField(default=0)),
                ('atk_multiplier', models.FloatField(default=1)),
                ('def_multiplier', models.FloatField(default=1)),
                ('spd_multiplier', models.FloatField(default=1)),
                ('move_description', models.CharField(max_length=150)),
                ('entity', models.ManyToManyField(to='PseudomonGo.entity')),
                ('entity_class', models.ManyToManyField(to='PseudomonGo.entityclass')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PseudomonGo.item')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Robot',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='owner_id',
            new_name='player',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='animal_type',
        ),
        migrations.RemoveField(
            model_name='player',
            name='username',
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='animal',
            name='attack',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='defense',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='health',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='speed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='num_animals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='move',
            name='status_inflicted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PseudomonGo.statuscondition'),
        ),
        migrations.AddField(
            model_name='entity',
            name='entity_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PseudomonGo.entityclass'),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PseudomonGo.entityclass'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PseudomonGo.entity'),
        ),
    ]
