# Generated by Django 3.2.12 on 2022-04-08 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PseudomonGo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='type',
            new_name='robot_type',
        ),
    ]
