# Generated by Django 4.0.3 on 2022-05-13 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PseudomonGo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='defense',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='health',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='speed',
        ),
    ]
