# Generated by Django 4.0.3 on 2022-04-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PseudomonGo', '0002_entity_entityclass_item_move_playerinventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_rarity',
            field=models.CharField(choices=[('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('E', 'Epic'), ('L', 'Legendary')], default='C', max_length=2),
        ),
        migrations.AddField(
            model_name='move',
            name='move_type',
            field=models.CharField(choices=[('A', 'Attack'), ('S', 'Status')], default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='move',
            name='target',
            field=models.CharField(choices=[('S', 'Self'), ('O', 'Opponent')], default='O', max_length=2),
        ),
    ]
