# Generated by Django 4.0.3 on 2022-04-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PseudomonGo', '0002_player_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerinventory',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='playerinventory',
            old_name='player_id',
            new_name='player',
        ),
        migrations.AddField(
            model_name='entity',
            name='Base_def',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='entity',
            name='Base_hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='entity',
            name='Base_spd',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='entity',
            name='base_atk',
            field=models.IntegerField(default=75),
        ),
        migrations.AddField(
            model_name='item',
            name='item_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='move',
            name='accuracy',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='playerinventory',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
