# Generated by Django 4.0.3 on 2022-05-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PseudomonGo', '0002_rename_attack_entity_base_atk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='entity',
            field=models.ManyToManyField(related_name='moves', to='PseudomonGo.entity'),
        ),
    ]
