# Generated by Django 4.0.3 on 2022-05-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PseudomonGo', '0003_alter_move_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='atk_multiplier',
        ),
        migrations.RemoveField(
            model_name='move',
            name='def_multiplier',
        ),
        migrations.RemoveField(
            model_name='move',
            name='spd_multiplier',
        ),
        migrations.AddField(
            model_name='move',
            name='atk_stage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='move',
            name='def_stage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='move',
            name='spd_stage',
            field=models.IntegerField(default=0),
        ),
    ]
