# Generated by Django 4.0.3 on 2022-04-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PseudomonGo', '0004_merge_20220427_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='infliction_chance',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='move',
            name='move_description',
            field=models.CharField(max_length=500),
        ),
    ]
